### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by zhangfq-chemistry** [HarrievG/BGFXTest#1]
I have download https://github.com/bkaradzic/bgfx.cmake and installed (sudo make && make install) on ubuntu.  But the BGFXTest Could not find a package configuration file provided by "BX" with any of the following names:
    BXConfig.cmake
    bx-config.cmake

**Comment by HarrievG** [comment]
Yes, I was also not able to get that repo to compile properly with CMAKE.

You have to install bgfx with vcpkg from the port folder.
It will use

https://www.github.com/HarrievG/BGFXTest/tree/main/.vcpkg%2Fports%2Fbx%2Fportfile.cmake

I don't remember ATM why that "original" cmake didn't work.
You can try to open a issue at the repo you pulled it from. If you get bgfx
compiled properly with vcpkg from that main repo, let me know and I'll
integrate it.

-Harry

**Comment by HarrievG** [comment]
FYI :
I have not tested Ubuntu. You will need to modify the compileshaders.bat to
some bash script. The shader for text is embedded so that one is fine.

You probably also need to modify some idsys calls in main.cpp to compile on
UNIX. I advise to a look at
https://github.com/dhewm/dhewm3
That source tree is where idlib and idFramework is based of so you just
have to take/add the correct UNIX stuff. It will take you some effort, but
it should not be very hard to do.

Good luck!
